version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker build -t aspnetapp -f Dockerfile .

     # deploy the image
     - run: |         
         docker login --username=$USERNAME --password=$API_KEY lifeorganizer.azurecr.io
         docker tag aspnetapp lifeorganizer.azurecr.io/$APP_NAME/web
         docker push lifeorganizer.azurecr.io/$APP_NAME/web
